version: '3'

services:
  mysqld:
    image: mysql:latest
    container_name: attendance
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

  attenance-app:
    image: tatu333/my-webapp:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysqld
    environment:
      MYSQL_HOST: mysqld
      

volumes:
  mysql-data:
