version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.3-jdk-11
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Build with Maven
          command: mvn -B package --file pom.xml

      - setup_remote_docker

      - run:
          name: Build & push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t tatu333/my-webapp .
            docker tag tatu333/my-webapp:latest tatu333/my-webapp:latest
            docker push tatu333/my-webapp:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - devops
