apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld
  template:
    metadata:
      labels:
        app: mysqld
    spec:
      containers:
        - name: mysqld
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-secret
#                  key: password
#            - name: MYSQL_USER
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-user
#                  key: user-name
            - name: MYSQL_DATABASE
              value: attendance
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
