apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfly
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
        - name: wildfly
          image: tatu333/my-webapp:latest
          env:
            - name: CONNECTION_URL
              value: jdbc:mysql://mysqld:3306/attendance
            - name: PASSWORD
              value: root
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-secret
#                  key: password
            - name: USER_NAME
              value: root
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-user
#                  key: user-name
          ports:
            - containerPort: 8080
